on: 
  workflow_dispatch:
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: repo list
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         super_secret: ${{ secrets.TOKEN }}
        run: |
          declare arr=("demo" "test-repo")
          for i in "${arr[@]}"
          do
           echo "$i"
           # or do whatever with individual element of the array
           curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer  ${{ secrets.demo }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Ayyappan-STC/"$i"/releases -d '{"tag_name":"sprint_date","target_commitish":"main","name":"sprint_date","body":"body","draft":false,"prerelease":false,"generate_release_notes":false}'
          done
