on: 
  workflow_dispatch:
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: repo list
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         super_secret: ${{ secrets.TOKEN }}
        run: |
          #curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer  ${{ secrets.demo }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Ayyappan-STC/demo/releases -d '{"tag_name":"sprint_date","target_commitish":"main","name":"sprint_date","body":"body","draft":false,"prerelease":false,"generate_release_notes":false}'
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.demo }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Ayyappan-STC/demo/branches/test/protection -d '{"required_status_checks":{"strict":false,"contexts":[]},"enforce_admins":false,"required_pull_request_reviews":{"dismissal_restrictions":{},"dismiss_stale_reviews":false,"require_code_owner_reviews":false,"required_approving_review_count":1,"require_last_push_approval":false,"bypass_pull_request_allowances":{}},"restrictions":{"users":[],"teams":[]},"required_linear_history":false,"allow_force_pushes":false,"allow_deletions":false,"block_creations":false,"required_conversation_resolution":false,"lock_branch":false,"allow_fork_syncing":false}'
